package com.example.wazitoecommerce.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val SPLASH_URL = "splash"
const val PROFILE_URL = "profile"
const val ADD_BIRDS_URL = "add_birds"
const val ADD_CATS_URL = "add_cats"
const val ADD_DOGS_URL = "add_dogs"
const val ADD_FISHS_URL = "add_fishs"
const val ADD_PETS_URL = "add_pets"
const val ADD_URL = "add"
const val UPDATE_URL = "update"
const val VIEW_PETS_URL = "view_pets"
const val UPDATE_PETS_URL = "update_pets"
const val VIEW_BIRDS_URL = "view_birds"
const val UPDATE_BIRDS_URL = "update_birds"
const val VIEW_CATS_URL = "view_cat"
const val UPDATE_CATS_URL = "update_cat"
const val VIEW_DOGS_URL = "view_dog"
const val UPDATE_DOGS_URL = "update_dog"
const val VIEW_FISHS_URL = "view_fish"
const val UPDATE_FISHS_URL = "update_fish"